name: Build Bun Project on Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.21

      - name: Install Dependencies
        run: |
          bun install

      - name: Build Project
        run: |
          bun build --target=bun-linux-x64 --compile --minify --sourcemap --bytecode index.ts --outfile artifacts/git-remote
          bun build --target=bun-windows-x64 --compile --minify --sourcemap index.ts --outfile artifacts/git-remote.exe
          
      - name: Upload Artifact for Linux
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: git-remote
          path: artifacts/git-remote
            
      - name: Upload Artifact for Windows
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: git-remote.exe
          path: artifacts/git-remote.exe
